/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;


import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;


/**
 *
 * @author Work
 */
public class SalvarERetornarSQLDatas extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame1
     */
    public SalvarERetornarSQLDatas() {
        initComponents();
        
       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfSalvoNoMySQL = new javax.swing.JTextField();
        tfRetornaMascara = new javax.swing.JTextField();
        jfCadastrando = new javax.swing.JFormattedTextField();
        jLCadastrando = new javax.swing.JLabel();
        jLRetorna = new javax.swing.JLabel();
        jLSalvoSQL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Salvar e Retornar datas no Sql (Extemplo)");

        tfSalvoNoMySQL.setEditable(false);
        tfSalvoNoMySQL.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfSalvoNoMySQLFocusGained(evt);
            }
        });

        tfRetornaMascara.setEditable(false);
        tfRetornaMascara.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfRetornaMascaraFocusGained(evt);
            }
        });

        try {
            jfCadastrando.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jfCadastrando.setToolTipText("");
        jfCadastrando.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jfCadastrandoFocusLost(evt);
            }
        });

        jLCadastrando.setText("Valor Cadastrando:");

        jLRetorna.setText("Data Que Retorna:");

        jLSalvoSQL.setText("Data Savo no MySQL:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLCadastrando)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jfCadastrando, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jLSalvoSQL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfSalvoNoMySQL, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jLRetorna)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfRetornaMascara, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jfCadastrando, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLCadastrando)
                    .addComponent(tfSalvoNoMySQL, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLSalvoSQL)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfRetornaMascara, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLRetorna)))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jfCadastrandoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jfCadastrandoFocusLost
        // EXEMPLO de Cadastro <------------------------------------------------------------
        this.jfCadastrando.setText(jfCadastrando.getText());
        
       
         System.out.println(jfCadastrando.getText());
    }//GEN-LAST:event_jfCadastrandoFocusLost

    private void tfRetornaMascaraFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfRetornaMascaraFocusGained
        // TODO EXEMPLO Retorna Data com Mask <------------------------------------------------------------
         String data10 = tfSalvoNoMySQL.getText();
         
        Date data = new Date();
        SimpleDateFormat formatar10 = new SimpleDateFormat("yyyy-MM-dd");
       
        try{
            data = formatar10.parse(data10);
        }catch (ParseException e) {
            e.printStackTrace();
        }
        SimpleDateFormat formatar20 = new SimpleDateFormat("dd/MM/yyyy");
        this.tfRetornaMascara.setText(formatar20.format(data));
    

        System.out.println(data);
        System.out.println(data);
 
        System.out.println(formatar10.format(data));
    }//GEN-LAST:event_tfRetornaMascaraFocusGained

    private void tfSalvoNoMySQLFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfSalvoNoMySQLFocusGained
        // EXEMPLO de Salvar no SQL <------------------------------------------------------------
        String data3 = jfCadastrando.getText();

        Date data = new Date();
        SimpleDateFormat formatar = new SimpleDateFormat("dd/MM/yyyy");
       
        try{
            data = formatar.parse(data3);
        }catch (ParseException e) {
            e.printStackTrace();
        }
       SimpleDateFormat formatar1 = new SimpleDateFormat("yyyy-MM-dd");
        this.tfSalvoNoMySQL.setText(formatar1.format(data));
    

        System.out.println(data);
        System.out.println(data);
        System.out.println(formatar.format(data));
        System.out.println(formatar1.format(data));
    }//GEN-LAST:event_tfSalvoNoMySQLFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SalvarERetornarSQLDatas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SalvarERetornarSQLDatas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SalvarERetornarSQLDatas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SalvarERetornarSQLDatas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SalvarERetornarSQLDatas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLCadastrando;
    private javax.swing.JLabel jLRetorna;
    private javax.swing.JLabel jLSalvoSQL;
    private javax.swing.JFormattedTextField jfCadastrando;
    private javax.swing.JTextField tfRetornaMascara;
    private javax.swing.JTextField tfSalvoNoMySQL;
    // End of variables declaration//GEN-END:variables

    private void getTime() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private String formt(Date data) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
